Repository matrix-org/matrix-spec-proposals, pull requests merged in 2019-02, with the labels that each got.

#1831 MSC1831: Change the order of .well-known and SRV discovery techniques
  proposals/1831-srv-after-wellknown.md
Labels: disposition-merge, merged, proposal, proposal-in-review

#1819 MSC:1819 Remove Presence Lists
  proposals/1819-remove-presence-lists.md
Labels: disposition-merge, merged, proposal

#1874 Add M_RESOURCE_LIMIT_EXCEEDED
  changelogs/client_server/newsfragments/1874.feature
  specification/client_server_api.rst
Labels: c2s r0.5.0

#1873 Add routes for retrieving account data
  api/client-server/account-data.yaml
  changelogs/client_server/newsfragments/1873.new
Labels: c2s r0.5.0

#1879 Correctly nest the capabilities response object
  api/client-server/capabilities.yaml
  changelogs/client_server/newsfragments/1879.feature
Labels: c2s r0.5.0

#1846 Fix changelog generation for non-default versions
  meta/releasing_a_spec.md
  scripts/templating/matrix_templates/sections.py
  scripts/templating/matrix_templates/units.py
Labels: c2s r0.5.0

#1866 Add proposal for invite error code for unsupported room version
  proposals/1866-invite-unsupported-version-error-code.md
Labels: c2s r0.5.0, disposition-merge, finished-final-comment-period, proposal, proposal-in-review
