Repository matrix-org/matrix-spec-proposals, pull requests merged in 2019-06, with the labels that each got.

#1717 MSC1717: common definitions for key verification methods
  proposals/1717-key_verification.md
Labels: disposition-merge, e2e, finished-final-comment-period, proposal, proposal-in-review

#2057 Clarify what the client should receiving on email resending
  api/identity/definitions/request_email_validation.yaml
  changelogs/identity_service/newsfragments/2057.clarification
Labels: Matrix 1.0

#2069 Clarify the order events in chunk are returned in for /messages
  api/client-server/message_pagination.yaml
  changelogs/client_server/newsfragments/2069.clarification
Labels: Matrix 1.0

#1719 MSC1719: olm session unwedging
  proposals/1719-olm_unwedging.md
Labels: disposition-merge, e2e, finished-final-comment-period, proposal, spec-pr-in-review

#2059 Add Olm unwedging
  changelogs/client_server/newsfragments/2059.feature
  event-schemas/examples/m.dummy
  event-schemas/schema/m.dummy
  specification/modules/end_to_end_encryption.rst
Labels: Matrix 1.0

#2052 Change reference for definition of push rule condition kinds
  api/client-server/definitions/push_condition.yaml
  changelogs/client_server/newsfragments/2052.clarification
Labels: Matrix 1.0

#2025 Fix third party signed definitions for join APIs
  api/client-server/definitions/third_party_signed.yaml
  api/client-server/joining.yaml
  changelogs/client_server/newsfragments/2025.clarification
  specification/modules/third_party_invites.rst
Labels: Matrix 1.0

#2056 Add a table to show how changes in membership should be interpreted
  changelogs/client_server/newsfragments/2056.clarification
  event-schemas/schema/m.room.member
  scripts/css/tables.css
Labels: Matrix 1.0

#2090 Clarify when authorization and rate-limiting are not applicable
  changelogs/client_server/newsfragments/2090.clarification
  scripts/templating/matrix_templates/templates/http-api.tmpl
Labels: Matrix 1.0

#2030 Spec MSISDN UIA support
  api/client-server/registration.yaml
  changelogs/client_server/newsfragments/2030.feature
  specification/client_server_api.rst
Labels: Matrix 1.0

#2095 Clarify how many PDUs are in a given transaction object
  api/server-server/backfill.yaml
  api/server-server/definitions/single_pdu_transaction.yaml
  api/server-server/definitions/unlimited_pdu_transaction.yaml
  api/server-server/events.yaml
  changelogs/server_server/newsfragments/2095.clarification
Labels: Matrix 1.0

#2067 Clarify exactly what StrippedState is
  api/client-server/sync.yaml
  api/server-server/invites-v1.yaml
  api/server-server/invites-v2.yaml
  changelogs/client_server/newsfragments/2067.clarification
  changelogs/server_server/newsfragments/2067.clarification
  event-schemas/check_examples.py
  event-schemas/examples/invite_room_state.json
  event-schemas/examples/m.room.member$invite_room_state
  event-schemas/schema/m.room.member
  event-schemas/schema/stripped_state.yaml
Labels: Matrix 1.0

#2046 Spec 3PID unbind API
  api/client-server/administrative_contact.yaml
  api/client-server/registration.yaml
  api/identity/associations.yaml
  changelogs/client_server/newsfragments/2046.feature
  changelogs/identity_service/newsfragments/2046.new
  proposals/1915-unbind-identity-server-param.md
Labels: Matrix 1.0

#2054 Clarify that UIA stages cannot be attempted twice
  changelogs/client_server/newsfragments/2054.clarification
  specification/client_server_api.rst
Labels: Matrix 1.0

#2047 Fix test vectors with invalid JSON and signature
  specification/appendices/test_vectors.rst
Labels: Matrix 1.0

#2081 Clarify which servers are supposed to sign events
  changelogs/server_server/newsfragments/2081.clarification
  specification/server_server_api.rst
Labels: Matrix 1.0

#2055 Clarify guest accounts and `auth` usage on /register
  api/client-server/registration.yaml
  changelogs/client_server/newsfragments/2055.clarification
Labels: Matrix 1.0

#2082 Make v4 the "default" room version
  specification/index.rst
Labels: Matrix 1.0

#2086 Clarify that the default s2s transport is JSON over HTTP
  changelogs/identity_service/newsfragments/2086.clarification
  specification/client_server_api.rst
  specification/server_server_api.rst
Labels: Matrix 1.0

#2072 Spec SAS verification and the common key verification framework
  changelogs/client_server/newsfragments/2072.feature
  data-definitions/sas-emoji.json
  event-schemas/examples/m.key.verification.accept
  event-schemas/examples/m.key.verification.cancel
  event-schemas/examples/m.key.verification.key
  event-schemas/examples/m.key.verification.mac
  event-schemas/examples/m.key.verification.request
  event-schemas/examples/m.key.verification.start
  event-schemas/examples/m.key.verification.start$m.sas.v1
  event-schemas/schema/m.key.verification.accept
  event-schemas/schema/m.key.verification.cancel
  event-schemas/schema/m.key.verification.key
  event-schemas/schema/m.key.verification.mac
  event-schemas/schema/m.key.verification.request
  event-schemas/schema/m.key.verification.start
  event-schemas/schema/m.key.verification.start$m.sas.v1
  scripts/continuserv/main.go
  scripts/templating/matrix_templates/sections.py
  scripts/templating/matrix_templates/units.py
  specification/modules/end_to_end_encryption.rst
Labels: Matrix 1.0

#1779 MSC1779: Proposal for Open Governance for Matrix.org (v2)
  proposals/1779-open-governance.md
  specification/proposals_intro.rst
Labels: disposition-merge, proposal, proposal-pr, spec-pr-in-review

#2089 Clarify when and where CORS headers should be returned
  changelogs/client_server/newsfragments/2089.clarification
  specification/client_server_api.rst
Labels: Matrix 1.0

#2084 Touchups on the s2s swagger definitions
  api/server-server/leaving.yaml
  api/server-server/query.yaml
  api/server-server/user_devices.yaml
  api/server-server/version.yaml
  api/server-server/wellknown.yaml
Labels: Matrix 1.0

#2077 MSC2077: room v5
  proposals/2077-rooms-v5.md
Labels: disposition-merge, finished-final-comment-period, proposal, spec-pr-in-review

#2076 MSC2076: Enforce key-validity periods when validating event signatures
  proposals/2076-enforce-validity-periods.md
Labels: disposition-merge, finished-final-comment-period, proposal, spec-pr-in-review

#2091 Clarify that /register must produce valid Matrix User IDs
  api/client-server/registration.yaml
  changelogs/client_server/newsfragments/2091.clarification
Labels: Matrix 1.0

#2098 Clarify what a "module" is and update feature profiles for clients
  changelogs/client_server/newsfragments/2098.clarification
  specification/feature_profiles.rst
  specification/modules.rst
  specification/modules/_template.rst
Labels: Matrix 1.0

#2078 MSC2078: Sending Third-Party Request Tokens via the Homeserver
  proposals/2078-homeserver-password-resets.md
Labels: disposition-merge, finished-final-comment-period, proposal, spec-pr-in-review

#2088 Merge GET/PUT /state/:event_type endpoints
  api/client-server/room_state.yaml
  api/client-server/rooms.yaml
  changelogs/client_server/newsfragments/2088.clarification
Labels: Matrix 1.0

#2096 Clarify how notification counts are calculated in /sync
  api/client-server/sync.yaml
  changelogs/client_server/newsfragments/2097.clarification
  specification/modules/push.rst
  specification/modules/receipts.rst
Labels: Matrix 1.0

#2097 Specify some of the common concepts for Matrix in the index
  api/server-server/keys_query.yaml
  api/server-server/keys_server.yaml
  changelogs/server_server/newsfragments/2097.clarification
  specification/index.rst
Labels: Matrix 1.0

#2104 Clarify that the common identifier format can be broken
  specification/appendices/identifier_grammar.rst
Labels: Matrix 1.0

#2068 Refactor documentation for content/media repository
  api/client-server/content-repo.yaml
  api/client-server/room_state.yaml
  changelogs/client_server/newsfragments/2068.clarification
  event-schemas/examples/m.room.member
  event-schemas/examples/m.room.member$invite_room_state
  event-schemas/examples/m.room.member$third_party_invite
  event-schemas/schema/core-event-schema/msgtype_infos/image_info.yaml
  event-schemas/schema/m.room.message$m.audio
  event-schemas/schema/m.room.message$m.file
  event-schemas/schema/m.room.message$m.image
  event-schemas/schema/m.room.message$m.video
  specification/modules/content_repo.rst
Labels: Matrix 1.0

#2080 Spec v5 rooms: Key validity
  api/server-server/definitions/keys.yaml
  changelogs/server_server/newsfragments/2080.clarification
  specification/index.rst
  specification/rooms/v5.rst
  specification/targets.yaml
Labels: Matrix 1.0

#2101 Add submit_url field to requestToken responses, clarify HS's can send tokens themselves
  api/client-server/administrative_contact.yaml
  api/client-server/definitions/request_token_response.yaml
  api/client-server/registration.yaml
  api/identity/definitions/request_email_validation.yaml
  api/identity/definitions/request_msisdn_validation.yaml
  changelogs/client_server/newsfragments/2101.breaking
  specification/client_server_api.rst
Labels: Matrix 1.0

#2035 Spec lazy-loading room members
  api/client-server/definitions/room_event_filter.yaml
  api/client-server/definitions/sync_filter.yaml
  api/client-server/event_context.yaml
  api/client-server/message_pagination.yaml
  api/client-server/rooms.yaml
  api/client-server/sync.yaml
  changelogs/client_server/newsfragments/2035.feature
  specification/client_server_api.rst
  specification/modules/instant_messaging.rst
Labels: Matrix 1.0

#2083 Clarify the key object definition for the key management API
  api/client-server/keys.yaml
  api/server-server/user_keys.yaml
  changelogs/client_server/newsfragments/2083.clarification
  changelogs/server_server/newsfragments/2083.clarification
Labels: Matrix 1.0

#2087 Reorganize event structure in c2s spec and clarify event capabilities
  changelogs/client_server/newsfragments/2087.clarification
  event-schemas/schema/core-event-schema/room_event.yaml
  event-schemas/schema/core-event-schema/state_event.yaml
  scripts/templating/matrix_templates/units.py
  specification/client_server_api.rst
  specification/events.rst
  specification/index.rst
  specification/targets.yaml
Labels: Matrix 1.0

#2099 Declare Matrix 1.0 in the index
  specification/index.rst
Labels: Matrix 1.0
