Repository matrix-org/matrix-spec-proposals, pull requests merged in 2020-05, with the labels that each got.

#2457 MSC2457: Invalidating devices during password modification
  proposals/2457-password-modification-invalidating-devices.md
Labels: disposition-merge, final-comment-period, kind:maintenance, proposal

#2454 MSC2454: Support UI interactive auth for SSO
  proposals/2454-ui-interactive-auth-for-sso.md
Labels: finished-final-comment-period, kind:feature, proposal

#2526 MSC2526: Add ability to delete key backups
  proposals/2526-add-delete-backup.md
Labels: finished-final-comment-period, proposal

#2559 Make backfill wording clearer
  api/server-server/backfill.yaml
Labels: clarification, s2s

#2472 MSC2472: Symmetric SSSS
  proposals/1946-secure_server-side_storage.md
  proposals/2472-symmetric-ssss.md
Labels: finished-final-comment-period, kind:core, proposal

#2540 MSC2540: Stricter event validation: JSON compliance
  proposals/2540-stricter-event-validation.md
Labels: kind:maintenance, proposal, spec-pr-in-review

#2240 MSC2240: Room version 6
  proposals/2240-rooms-v6.md
Labels: kind:core, proposal, spec-pr-in-review

#2209 MSC2209: Alter auth rules to check notifications in m.room.power_levels
  proposals/2209-auth-rules-other-keys-in-m.room.power.levels.md
Labels: kind:core, proposal, spec-pr-in-review

#2572 Update MSC1779 to forward link to matrix.org/foundation
  proposals/1779-open-governance.md
Labels: next-release

#2574 Remove claim that profile info is exclusively managed by the server
  changelogs/client_server/newsfragments/2574.clarification
  event-schemas/schema/m.room.member
Labels: next-release

#2576 Clarify that server names are at least 1 character
  specification/appendices/identifier_grammar.rst
Labels: next-release

#2577 Fix more typos throughout the specification
  api/server-server/keys_server.yaml
  changelogs/server_server/newsfragments/2577.clarification
Labels: next-release

#2571 Clarify that a creation event and member event are needed for createRoom
  api/client-server/create_room.yaml
  changelogs/client_server/newsfragments/2571.clarification
Labels: next-release

#2546 Spec soft-logout per MSC1466
  api/client-server/registration.yaml
  changelogs/client_server/newsfragments/2546.feature
  specification/client_server_api.rst
Labels: next-release

#2570 Clarify which server names to sign requests with
  changelogs/server_server/newsfragments/2570.clarification
  specification/server_server_api.rst
Labels: next-release

#2562 Add spec for new alias handling (client-server)
  api/client-server/directory.yaml
  api/client-server/room_state.yaml
  changelogs/client_server/newsfragments/2562.feature
  changelogs/client_server/newsfragments/2562.new
  event-schemas/examples/m.room.aliases
  event-schemas/examples/m.room.canonical_alias
  event-schemas/schema/m.room.aliases
  event-schemas/schema/m.room.canonical_alias
  specification/client_server_api.rst
  specification/modules/instant_messaging.rst
Labels: next-release, release-blocker

#2575 Clarify the auth_chain and state requirements for /send_join
  api/server-server/definitions/send_join_response.yaml
  api/server-server/joins-v1.yaml
  api/server-server/joins-v2.yaml
  changelogs/server_server/newsfragments/2575.clarification
Labels: next-release

#2563 Room Version 6
  changelogs/client_server/newsfragments/2563.clarification
  scripts/css/pygments.css
  scripts/gendoc.py
  specification/appendices/signing_json.rst
  specification/client_server_api.rst
  specification/index.rst
  specification/rooms/v1.rst
  specification/rooms/v6.rst
  specification/targets.yaml
Labels: next-release, release-blocker
